import type { PrismaClient } from "@ai-os/database";

export type DbClient = Pick<
  PrismaClient,
  | "opportunity"
  | "opportunityEvidence"
  | "affiliateLink"
  | "affiliateLinkClick"
  | "contentAsset"
  | "revenueEvent"
  | "profitRecord"
  | "bossCommand"
  | "bossPlan"
  | "bossTask"
  | "bossAction"
  | "bossAuditLog"
  | "bossApproval"
  | "bossToolCall"
  | "bossDecision"
  | "bossMemory"
  | "bossLesson"
  | "sellerAccount"
  | "sellerPermission"
  | "product"
  | "productVariant"
  | "sellerListing"
  | "sellerListingVersion"
  | "sellerInventory"
  | "sellerOrder"
  | "sellerOrderItem"
  | "sellerReturn"
  | "sellerSettlement"
>;